import type { Article } from '../../../types/article'

export const articlesEn: Article[] = [
  {
    id: 'metrics-metrik-nedir',
    slug: 'metrik-nedir',
    title: 'What is a Metric?',
    excerpt: 'Learn about the metric concept in Clixer and what it does.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['metric', 'kpi', 'basic', 'concept'],
    images: [],
    relatedArticles: ['metrics-yeni-metrik-olusturma', 'getting-started-temel-kavramlar'],
    lastUpdated: '2026-01-27',
    readingTime: 5,
    order: 1,
    content: `
# What is a Metric?

A metric is a meaningful value calculated from data. Every number, chart, or table displayed on dashboards is connected to a metric.

## Metric Components

A metric consists of these components:

| Component | Description | Example |
|-----------|-------------|---------|
| Dataset | Data source | Daily Sales |
| Column | Field to calculate | amount, quantity |
| Calculation | Operation type | SUM, AVG, COUNT |
| Visualization | Display method | Card, Chart, Table |

## Metric Types

### 1. Summary Metrics
Returns a single value: Total, Average, Count

**Example:** Total Revenue = SUM(amount)

### 2. Trend Metrics
Returns time-based values.

**Example:** Daily Sales Trend = SUM(amount) GROUP BY date

### 3. List Metrics
Returns multiple rows.

**Example:** Store List = SELECT store, SUM(amount) GROUP BY store

## Metric vs Widget

| Metric | Widget |
|--------|--------|
| What to calculate | How to display |
| Data definition | Visual component |
| Reusable | Design-specific |

A metric can be used in multiple widgets.

## Metric Creation Modes

### Column Selection Mode
For simple metrics. Select a column from dataset and specify calculation type.

### SQL Mode
For complex metrics. Write custom SQL queries.

## Next Steps

- [Create New Metric](/metrics/yeni-metrik-olusturma)
- [Column Selection Mode](/metrics/kolon-secimi-modu)
- [SQL Mode](/metrics/sql-modu)
`
  },
  {
    id: 'metrics-yeni-metrik-olusturma',
    slug: 'yeni-metrik-olusturma',
    title: 'Create New Metric',
    excerpt: 'Create a new metric step by step.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['metric', 'create', 'new', 'step by step'],
    images: [],
    relatedArticles: ['metrics-kolon-secimi-modu', 'metrics-sql-modu'],
    lastUpdated: '2026-01-27',
    readingTime: 6,
    order: 2,
    content: `
# Create New Metric

In this guide, you'll create a new metric step by step.

## Open Metrics Page

1. Select **Designer** from the left menu
2. Click the **Metrics** tab
3. Click **+ New Metric** button

## Basic Information

### Metric Name
Give a meaningful name:
- ✅ "Total Revenue"
- ✅ "Daily Visitor Count"
- ❌ "Metric1"

### Metric Code
Automatically generated by the system. No need to change.

## Dataset Selection

1. Select data source from **Dataset** dropdown
2. Dataset columns are automatically loaded

> 💡 If no dataset exists, check [Create Dataset](/data/dataset-olusturma) guide first.

## Select Calculation Mode

### Column Selection
For simple metrics:
- Select column
- Specify calculation type (SUM, AVG, COUNT)

### SQL Mode
For complex metrics:
- Write custom SQL query
- Use UNION, JOIN operations

## Visualization Type

Select how the metric will be displayed:

| Type | Usage |
|------|-------|
| Card | Single value |
| Chart | Trend |
| Table | List |
| Gauge | Target tracking |

## Save

1. Fill all fields
2. Test with **Preview**
3. Click **Save** button

## Next Steps

- [Calculation Types](/metrics/hesaplama-tipleri)
- [Format Settings](/metrics/format-ayarlari)
- [Comparison Settings](/metrics/karsilastirma-ayarlari)
`
  },
  {
    id: 'metrics-kolon-secimi-modu',
    slug: 'kolon-secimi-modu',
    title: 'Column Selection Mode',
    excerpt: 'Create simple metrics from dataset columns.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['column', 'selection', 'simple', 'metric'],
    images: [],
    relatedArticles: ['metrics-sql-modu', 'metrics-hesaplama-tipleri'],
    lastUpdated: '2026-01-27',
    readingTime: 5,
    order: 3,
    content: `
# Column Selection Mode

Column selection mode allows you to create simple metrics without SQL knowledge.

## When to Use?

- When calculating from a single column
- For simple sum, average, count operations
- When you want to quickly create a metric

## Step by Step

### 1. Select Dataset
Select data source from dropdown.

### 2. Select Column
Dataset columns are listed. Select the column to calculate.

### 3. Specify Calculation Type

| Type | Description | Example |
|------|-------------|---------|
| SUM | Total | Total sales amount |
| AVG | Average | Average basket amount |
| COUNT | Count | Transaction count |
| MIN | Minimum | Lowest price |
| MAX | Maximum | Highest sale |
| COUNT DISTINCT | Unique count | Unique customer count |

### 4. Grouping (Optional)
Select grouping column for trend or list metrics:
- Date: Daily/Weekly/Monthly trend
- Category: Category-based distribution
- Store: Store-based list

## Example: Total Revenue Metric

1. Dataset: "Daily Sales"
2. Column: "amount"
3. Calculation: SUM
4. Grouping: None (single value)

Result: Total revenue in selected date range

## Example: Daily Sales Trend

1. Dataset: "Daily Sales"
2. Column: "amount"
3. Calculation: SUM
4. Grouping: "date" (daily)

Result: Separate total for each day

## Limitations

Column selection mode cannot:
- Join multiple tables
- Complex WHERE conditions
- Subqueries

Use [SQL Mode](/metrics/sql-modu) for these cases.
`
  },
  {
    id: 'metrics-sql-modu',
    slug: 'sql-modu',
    title: 'SQL Mode',
    excerpt: 'Create complex metrics with custom SQL queries.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['sql', 'query', 'complex', 'advanced'],
    images: [],
    relatedArticles: ['metrics-kolon-secimi-modu', 'metrics-filtre-kosullari'],
    lastUpdated: '2026-01-27',
    readingTime: 8,
    order: 4,
    content: `
# SQL Mode

SQL mode is used for complex calculations and custom queries.

## When to Use?

- When joining multiple tables (UNION, JOIN)
- When complex WHERE conditions are needed
- When using subqueries
- When custom calculations are required

## Enable SQL Mode

1. Turn on **SQL Mode** toggle in metric edit screen
2. SQL editor appears

## Basic Rules

### 1. Start with SELECT
\`\`\`sql
SELECT SUM(amount) as value
FROM daily_sales
\`\`\`

### 2. Use Aliases
Give aliases to result columns:
\`\`\`sql
SELECT 
  SUM(amount) as value,
  date as date
\`\`\`

### 3. Date Filter Placeholder
Use placeholders for date filters:
\`\`\`sql
WHERE date BETWEEN {start_date} AND {end_date}
\`\`\`

## Example Queries

### Simple Total
\`\`\`sql
SELECT SUM(amount) as value
FROM daily_sales
WHERE date BETWEEN {start_date} AND {end_date}
\`\`\`

### Trend Query
\`\`\`sql
SELECT 
  date,
  SUM(amount) as value
FROM daily_sales
WHERE date BETWEEN {start_date} AND {end_date}
GROUP BY date
ORDER BY date
\`\`\`

### UNION Combination
\`\`\`sql
SELECT 'Online' as channel, SUM(amount) as value
FROM online_sales
WHERE date BETWEEN {start_date} AND {end_date}

UNION ALL

SELECT 'Store' as channel, SUM(amount) as value
FROM store_sales
WHERE date BETWEEN {start_date} AND {end_date}
\`\`\`

## Placeholders

| Placeholder | Description |
|-------------|-------------|
| {start_date} | Selected start date |
| {end_date} | Selected end date |
| {prev_start_date} | Comparison start |
| {prev_end_date} | Comparison end |
| {store_id} | Selected store ID |
| {region_id} | Selected region ID |

## Preview and Test

1. Write SQL
2. Click **Preview** button
3. Check results
4. Fix if errors

> ⚠️ **Warning:** Only SELECT queries can be executed. INSERT, UPDATE, DELETE are forbidden.

## Tips

> 💡 Test complex queries in database tool first.

> 💡 Use LIMIT to improve preview performance.

> 💡 Write aliases without special characters.
`
  },
  {
    id: 'metrics-hesaplama-tipleri',
    slug: 'hesaplama-tipleri',
    title: 'Calculation Types',
    excerpt: 'Learn about SUM, AVG, COUNT and other calculation types.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['calculation', 'sum', 'avg', 'count', 'aggregation'],
    images: [],
    relatedArticles: ['metrics-kolon-secimi-modu', 'metrics-format-ayarlari'],
    lastUpdated: '2026-01-27',
    readingTime: 5,
    order: 5,
    content: `
# Calculation Types

Learn about calculation types you can use when creating metrics.

## Basic Calculation Types

### SUM (Total)
Sum of all values in selected column.

**Usage:** Total revenue, total quantity

### AVG (Average)
Average of values in selected column.

**Usage:** Average basket amount, average price

### COUNT (Count)
Number of rows.

**Usage:** Transaction count, order count

### COUNT DISTINCT (Unique Count)
Number of unique values.

**Usage:** Unique customers, unique products

### MIN (Minimum)
Smallest value.

**Usage:** Lowest price, first date

### MAX (Maximum)
Largest value.

**Usage:** Highest sale, last date

## Calculation Type Selection Guide

| Need | Calculation Type |
|------|------------------|
| Total value | SUM |
| Average value | AVG |
| How many | COUNT |
| How many different | COUNT DISTINCT |
| Lowest | MIN |
| Highest | MAX |

## Tips

> 💡 NULL values are automatically skipped in calculations.

> 💡 COUNT(*) counts NULL, COUNT(column) excludes NULL.

> 💡 Be careful about the effect of 0 values when using AVG.
`
  },
  {
    id: 'metrics-gorsellestime-tipleri',
    slug: 'gorsellestime-tipleri',
    title: 'Visualization Types',
    excerpt: 'Display metrics as cards, charts, or tables.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['visualization', 'card', 'chart', 'table', 'widget'],
    images: [],
    relatedArticles: ['designer-widget-turleri', 'metrics-format-ayarlari'],
    lastUpdated: '2026-01-27',
    readingTime: 5,
    order: 6,
    content: `
# Visualization Types

Determine how the metric will appear on the dashboard.

## What is Visualization Type?

The visualization type you select when defining a metric determines which widget types this metric can be used in.

## Types

### CARD
Shows a single value.

**Compatible Widgets:** Big Card, Mini Card, Big Number

### CHART
Time series or categorical data.

**Compatible Widgets:** Line, Bar, Area, Pie Chart

### LIST
Multiple rows, ranking list.

**Compatible Widgets:** Ranking List

### DATA_GRID
Detailed table view.

**Compatible Widgets:** Data Table

### GAUGE
For target tracking.

**Compatible Widgets:** Gauge, Progress Ring

## Type Selection Guide

| Need | Visualization Type |
|------|-------------------|
| Single KPI | CARD |
| See trend | CHART |
| TOP 10 list | LIST |
| Detailed table | DATA_GRID |
| Target tracking | GAUGE |

## Tips

> 💡 Data won't appear in widget if wrong type is selected.

> 💡 CHART type requires a grouping column.

> 💡 Sorting and LIMIT are recommended for LIST type.
`
  },
  {
    id: 'metrics-karsilastirma-ayarlari',
    slug: 'karsilastirma-ayarlari',
    title: 'Comparison Settings',
    excerpt: 'Make period comparisons like YoY, MoM, WoW.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['comparison', 'yoy', 'mom', 'wow', 'trend'],
    images: [],
    relatedArticles: ['metrics-lfl-karsilastirma', 'metrics-format-ayarlari'],
    lastUpdated: '2026-01-27',
    readingTime: 6,
    order: 7,
    content: `
# Comparison Settings

Compare your metrics with previous periods.

## What is Comparison?

Comparison allows you to compare the value in the selected period with a previous period. This way you can see if performance has increased or decreased.

## Comparison Types

### YoY (Year over Year)
Comparison with the same period last year.

**Example:** January 2026 vs January 2025

### MoM (Month over Month)
Comparison with previous month.

**Example:** January 2026 vs December 2025

### WoW (Week over Week)
Comparison with previous week.

**Example:** This week vs last week

### DoD (Day over Day)
Comparison with previous day.

**Example:** Today vs yesterday

### Custom Period
Manual date range selection.

## Enable Comparison

1. Find **Comparison** section in metric edit screen
2. Select **Comparison Type** (YoY, MoM, etc.)
3. Save

## Widget Display

Metrics with active comparison appear in widget like this:

\`\`\`
Total Revenue
$1,250,000
▲ +12.5% vs last year
\`\`\`

- ▲ Green: Increase
- ▼ Red: Decrease

## Reverse Logic

For some metrics, decrease is good (e.g., cost, returns). In this case:

1. Check **Reverse Logic** option
2. Decrease shows green, increase shows red

## Tips

> 💡 YoY is not affected by seasonality, more reliable.

> 💡 MoM is suitable for short-term trends.

> ⚠️ "N/A" appears if no data for comparison period.
`
  },
  {
    id: 'metrics-lfl-karsilastirma',
    slug: 'lfl-karsilastirma',
    title: 'LFL (Like-for-Like) Comparison',
    excerpt: 'Perform comparable store analysis.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['lfl', 'like-for-like', 'comparison', 'store'],
    images: [],
    relatedArticles: ['metrics-lfl-takvim-ayarlari', 'metrics-karsilastirma-ayarlari'],
    lastUpdated: '2026-01-27',
    readingTime: 7,
    order: 8,
    content: `
# LFL (Like-for-Like) Comparison

LFL compares only stores that were open in both periods.

## What is LFL?

Like-for-Like (LFL) is comparable period analysis. It measures real performance change by excluding newly opened or closed stores.

## Why LFL?

### Standard Comparison Problem

| Period | Store Count | Revenue |
|--------|-------------|---------|
| 2025 | 100 | $10M |
| 2026 | 120 | $13M |

Appears to be 30% growth, but 20 new stores opened!

### Real Situation with LFL

| Period | Comparable Stores | Revenue |
|--------|-------------------|---------|
| 2025 | 100 | $10M |
| 2026 | 100 (same stores) | $10.5M |

Real growth is only 5%.

## How LFL Works

1. Stores open in both periods are identified
2. Only data from these stores is compared
3. New/closed stores are excluded

## LFL Setup

### 1. LFL Calendar Dataset
Dataset containing store open/close dates is required.

### 2. Metric Settings
1. Enable **LFL** option in metric edit screen
2. Select LFL calendar dataset
3. Map store ID

## Tips

> 💡 LFL is a standard metric in retail industry.

> 💡 LFL growth is important in investor reports.

> ⚠️ LFL calendar data must be kept up to date.
`
  },
  {
    id: 'metrics-format-ayarlari',
    slug: 'format-ayarlari',
    title: 'Format Settings',
    excerpt: 'Number format, prefix, suffix and other format settings.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['format', 'number', 'currency', 'percentage', 'display'],
    images: [],
    relatedArticles: ['metrics-gorsellestime-tipleri', 'metrics-hesaplama-tipleri'],
    lastUpdated: '2026-01-27',
    readingTime: 5,
    order: 9,
    content: `
# Format Settings

Customize how metric values are displayed.

## Number Format

### Decimal Places
How many decimal places to show.

| Setting | Example |
|---------|---------|
| 0 | 1,250 |
| 1 | 1,250.5 |
| 2 | 1,250.50 |

### Thousands Separator
Makes large numbers readable.

| Setting | Example |
|---------|---------|
| Off | 1250000 |
| On | 1,250,000 |

## Prefix

Text added before the value.

| Prefix | Example |
|--------|---------|
| $ | $1,250,000 |
| € | €1,250,000 |
| £ | £1,250,000 |

## Suffix

Text added after the value.

| Suffix | Example |
|--------|---------|
| % | 85% |
| units | 1,250 units |
| people | 500 people |

## Abbreviation

Abbreviates large numbers.

| Value | Abbreviation |
|-------|--------------|
| 1,000 | 1K |
| 1,000,000 | 1M |
| 1,000,000,000 | 1B |

## Tips

> 💡 Use consistent format, same currency across dashboard.

> 💡 Using abbreviation on mobile improves readability.

> 💡 Don't forget to multiply by 100 for percentage metrics.
`
  },
  {
    id: 'metrics-filtre-kosullari',
    slug: 'filtre-kosullari',
    title: 'Filter Conditions',
    excerpt: 'Add WHERE conditions to metrics.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['filter', 'where', 'condition', 'sql'],
    images: [],
    relatedArticles: ['metrics-sql-modu', 'metrics-group-by-kullanimi'],
    lastUpdated: '2026-01-27',
    readingTime: 5,
    order: 10,
    content: `
# Filter Conditions

Add fixed filter conditions to metrics.

## What is Filter Condition?

Fixed WHERE condition applied when metric is calculated. Filters specific to the metric, separate from dashboard filters.

## When to Use?

- To filter a specific category
- To exclude cancelled records
- To filter a specific status

## In Column Selection Mode

1. Open **Filter Conditions** section
2. Click **+ Add Condition**
3. Select column, operator, and value

### Operators

| Operator | Description | Example |
|----------|-------------|---------|
| = | Equal | category = 'Food' |
| != | Not equal | status != 'Cancelled' |
| > | Greater | amount > 100 |
| < | Less | amount < 1000 |
| IN | In list | category IN ('A', 'B') |
| LIKE | Similar | name LIKE '%market%' |

## In SQL Mode

Write WHERE condition directly:

\`\`\`sql
SELECT SUM(amount) as value
FROM sales
WHERE date BETWEEN {start_date} AND {end_date}
  AND category = 'Food'
  AND status != 'Cancelled'
\`\`\`

## Tips

> 💡 Filter conditions are independent of dashboard filters.

> 💡 Filter on indexed columns for performance.

> ⚠️ Too many conditions can affect query performance.
`
  },
  {
    id: 'metrics-group-by-kullanimi',
    slug: 'group-by-kullanimi',
    title: 'GROUP BY Usage',
    excerpt: 'Grouping and categorizing data.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['group by', 'grouping', 'category', 'sql'],
    images: [],
    relatedArticles: ['metrics-sql-modu', 'metrics-siralama-listesi'],
    lastUpdated: '2026-01-27',
    readingTime: 5,
    order: 11,
    content: `
# GROUP BY Usage

Learn about grouping and categorizing data.

## What is GROUP BY?

GROUP BY groups data by a specific column and performs separate calculations for each group.

## When to Use?

- For trend charts (date-based)
- For category-based distributions
- For store/region-based lists

## Basic Usage

\`\`\`sql
SELECT 
  category,
  SUM(amount) as total
FROM sales
GROUP BY category
\`\`\`

Result:
| category | total |
|----------|-------|
| Food | 500,000 |
| Beverage | 250,000 |
| Cleaning | 150,000 |

## Date-Based Grouping

### Daily
\`\`\`sql
GROUP BY date
\`\`\`

### Weekly
\`\`\`sql
GROUP BY toStartOfWeek(date)
\`\`\`

### Monthly
\`\`\`sql
GROUP BY toStartOfMonth(date)
\`\`\`

## Multiple Grouping

\`\`\`sql
SELECT 
  region,
  category,
  SUM(amount) as total
FROM sales
GROUP BY region, category
\`\`\`

## Tips

> 💡 Every non-aggregated column in SELECT must be in GROUP BY.

> 💡 Too much grouping can affect performance.

> 💡 Single grouping column is recommended for CHART type.
`
  },
  {
    id: 'metrics-siralama-listesi',
    slug: 'siralama-listesi',
    title: 'Ranking List (TOP N)',
    excerpt: 'Create lists like best selling products, top stores.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['ranking', 'top', 'list', 'sorting'],
    images: [],
    relatedArticles: ['metrics-group-by-kullanimi', 'designer-tablo-widget'],
    lastUpdated: '2026-01-27',
    readingTime: 5,
    order: 12,
    content: `
# Ranking List (TOP N)

List the best/worst performing items.

## What is Ranking List?

TOP N list shows the first N items sorted by a specific criterion.

## Use Cases

- Top 10 best selling products
- Top 5 highest revenue stores
- Lowest performing regions

## SQL Structure

\`\`\`sql
SELECT 
  product_name,
  SUM(quantity) as total_sales
FROM sales
WHERE date BETWEEN {start_date} AND {end_date}
GROUP BY product_name
ORDER BY total_sales DESC
LIMIT 10
\`\`\`

## Visualization

Select **LIST** visualization type for ranking list.

Use **Ranking List** as widget.

## Sort Direction

### Descending (DESC)
Highest to lowest. For "best" lists.

### Ascending (ASC)
Lowest to highest. For "worst" lists.

## LIMIT Setting

| LIMIT | Usage |
|-------|-------|
| 5 | Compact list |
| 10 | Standard TOP 10 |
| 20 | Detailed list |

## Tips

> 💡 Rank number is automatically shown in widget.

> 💡 You can enrich by adding percentage or change column.

> ⚠️ Very long lists reduce readability.
`
  },
  {
    id: 'metrics-veri-tablosu-metrigi',
    slug: 'veri-tablosu-metrigi',
    title: 'Data Table Metric',
    excerpt: 'Create metrics for detailed data tables.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['table', 'data grid', 'detail', 'list'],
    images: [],
    relatedArticles: ['designer-tablo-widget', 'metrics-group-by-kullanimi'],
    lastUpdated: '2026-01-27',
    readingTime: 5,
    order: 13,
    content: `
# Data Table Metric

Create DATA_GRID type metrics for detailed data tables.

## What is Data Table?

Data table is a detailed list view containing multiple columns and rows. Used for data like store lists, product details.

## Visualization Type

Select **DATA_GRID**. This type:
- Supports multiple columns
- Provides pagination
- Enables sorting and filtering

## SQL Structure

\`\`\`sql
SELECT 
  store_code,
  store_name,
  region,
  SUM(amount) as revenue,
  COUNT(*) as transaction_count,
  AVG(amount) as average_basket
FROM sales
WHERE date BETWEEN {start_date} AND {end_date}
GROUP BY store_code, store_name, region
ORDER BY revenue DESC
\`\`\`

## Column Definitions

Each SELECT column becomes a table column:

| Column | Description |
|--------|-------------|
| store_code | Store code |
| store_name | Store name |
| region | Region |
| revenue | Total revenue |
| transaction_count | Transaction count |
| average_basket | Average basket |

## Widget Usage

1. Add **Data Table** widget
2. Connect DATA_GRID type metric
3. Adjust column widths

## Performance Tips

> 💡 Use pagination for many rows.

> 💡 Don't add unnecessary columns.

> 💡 Sort by indexed columns.
`
  },
  {
    id: 'metrics-onizleme-ve-test',
    slug: 'onizleme-ve-test',
    title: 'Preview and Test',
    excerpt: 'Test the metric before saving.',
    category: 'metrics',
    categoryLabel: 'Metrics',
    tags: ['preview', 'test', 'debug', 'check'],
    images: [],
    relatedArticles: ['metrics-sql-modu', 'advanced-sorun-giderme'],
    lastUpdated: '2026-01-27',
    readingTime: 4,
    order: 14,
    content: `
# Preview and Test

Test that the metric works correctly before saving.

## What is Preview?

Preview runs the metric query and shows the result. You can check correctness before saving.

## How to Preview

1. Complete metric settings
2. Click **Preview** button
3. See data in result panel

## Preview Results

### Successful Preview
- Value is displayed
- Row count is shown
- Query time is reported

### Failed Preview
- Error message is displayed
- SQL error detail is given
- Fix suggestions are provided

## Common Errors

### Syntax Error
\`\`\`
Error: Syntax error near 'FORM'
\`\`\`
**Solution:** Check SQL spelling (FROM, not FORM)

### Column Not Found
\`\`\`
Error: Column 'amount' not found
\`\`\`
**Solution:** Check column name and dataset

### Type Mismatch
\`\`\`
Error: Cannot compare String with Int
\`\`\`
**Solution:** Check data types, use CAST if needed

## Test Scenarios

1. Test with **different date ranges**
2. Try **filter combinations**
3. Check **empty data situation**

## Performance Check

Pay attention to query time in preview:

| Time | Evaluation |
|------|------------|
| < 1 sec | Good |
| 1-5 sec | Acceptable |
| > 5 sec | Optimization needed |

## Tips

> 💡 Preview runs with LIMIT 100, save for full data.

> 💡 Test query in database tool first for SQL mode.

> ⚠️ Production may have different results even if preview succeeds.
`
  }
]
